services:
  - type: web
    name: uniconnect-server
    env: dotnet
    plan: free
    buildCommand: "dotnet publish UniConnect.Server/UniConnect.Server.csproj -c Release -o out"
    startCommand: "dotnet out/UniConnect.Server.dll"
    rootDir: UniConnect.Server
    autoDeploy: true
