services:
  - type: web
    name: uniconnect-server
    runtime: docker
    plan: free
    rootDir: UniConnect.Server
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:10000
    dockerfilePath: UniConnect.Server/Dockerfile